{% set name = "pyrundeck" %}
{% set version = "0.9.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrundeck-{{ version }}.tar.gz
  sha256: e46973d4ded02192f099c3c05a67c4c459a61d28316d40b0253116cf3c022258

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - requests

test:
  imports:
    - pyrundeck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pschmitt/pyrundeck
  summary: Python REST API client for Rundeck 2.6+
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
